#!/usr/bin/env python3
"""
MMseqs2 Cross-Strain Intergenic Region (IGR) Alignment & Synteny Analyzer.

This script performs cross-strain comparative genomics between Streptococcus pneumoniae D39V and TIGR4.
It processes BLAST-tabular format (.m8) alignment outputs generated by MMseqs2 easy-search and computes:
  1. Primary Synteny Statistics: Total alignment pairs, unique query coverage, target coverage.
  2. Sequence Identity Stratification: Breakdown by 100%, 90-99%, 80-89%, and <80% identity.
  3. Orthology Multiplicity: Differentiates clean 1-to-1 single-mapping orthologs from multi-mapping repeats (BOX/RUP/IS elements).
  4. Directional Comparisons: Optional forward (D39V -> TIGR4), reverse (TIGR4 -> D39V), or reciprocal best-hit (RBH) bidirectional analysis.
  5. Structural Orientation Stratification: Evaluates alignment conservation by IGR type (TANDEM, DIVERGENT, CONVERGENT).
  6. Cross-Validation: Optional validation against Nucmer colinear synteny blocks.

Usage:
  pixi run python src/analysis/analyze_mmseqs2_m8.py [--mode {forward,reverse,bidir}] [--separate-repeats] [--by-orientation]
"""

import csv
import argparse
import pandas as pd
import numpy as np
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
M8_FWD = ROOT / "output" / "intergenic" / "mmseqs2" / "cross" / "D39V_vs_TIGR4.m8"
M8_REV = ROOT / "output" / "intergenic" / "mmseqs2" / "cross" / "TIGR4_vs_D39V.m8"
D39V_TSV = ROOT / "output" / "intergenic" / "d39v" / "D39V_igrs.tsv"
TIGR4_TSV = ROOT / "output" / "intergenic" / "tigr4" / "TIGR4_igrs.tsv"

COLS = ["query", "target", "pident", "alnlen", "mismatch",
        "gapopen", "qstart", "qend", "tstart", "tend", "evalue", "bits"]



def load_igr_metadata(path: Path) -> dict:
    """Load intergenic region (IGR) metadata from TSV table into a dictionary keyed by igr_id.
    
    Reads genomic coordinates (start, end, length), orientation types (TANDEM, DIVERGENT, CONVERGENT),
    and flanking CDS identifiers (left_cds, right_cds).
    """
    igrs = {}
    with open(path, newline="") as f:
        for row in csv.DictReader(f, delimiter="\t"):
            igrs[row["igr_id"].strip("\r")] = row
    return igrs


def load_m8(path: Path) -> pd.DataFrame:
    """Load MMseqs2 BLAST-tabular (.m8) alignment file into a pandas DataFrame.
    
    Automatically normalizes percent identity (pident) values to a 0-100% scale.
    """
    df = pd.read_csv(path, sep="\t", header=None, names=COLS)
    if df["pident"].max() <= 1.0:
        df["pident_pct"] = df["pident"] * 100.0
    else:
        df["pident_pct"] = df["pident"]
    return df


def print_stats(df: pd.DataFrame, label: str, total_queries: int = None, total_targets: int = None):
    """Compute and print comprehensive alignment statistics for MMseqs2 cross-strain comparison.
    
    Metrics reported:
      - Total alignment hit pairs
      - Unique query coverage and percentage of strain IGR genome
      - Unique target coverage and percentage of target strain IGR genome
      - Mean and median sequence identity
      - Alignment length distribution (mean, min, max)
      - Identity breakdown (100% exact, >=90%, 80-89%, <80%)
      - Orthology multiplicity (1-to-1 unique mapping vs multi-mapping repeat elements)
    """
    n = len(df)
    uq = df["query"].nunique()
    ut = df["target"].nunique()
    qc = df["query"].value_counts()
    single = (qc == 1).sum()
    multi = (qc > 1).sum()

    exact = (df["pident_pct"] == 100.0).sum()
    high = ((df["pident_pct"] >= 90.0) & (df["pident_pct"] < 100.0)).sum()
    med = ((df["pident_pct"] >= 80.0) & (df["pident_pct"] < 90.0)).sum()
    low = (df["pident_pct"] < 80.0).sum()

    print(f"\n{'='*60}")
    print(f"  {label}")
    print(f"{'='*60}")
    print(f"  Pairs: {n:,}  |  Queries: {uq:,}  |  Targets: {ut:,}")
    if total_queries:
        print(f"  Query coverage: {uq}/{total_queries} ({uq/total_queries*100:.1f}%)")
    if total_targets:
        print(f"  Target coverage: {ut}/{total_targets} ({ut/total_targets*100:.1f}%)")
    print(f"  Mean identity: {df['pident_pct'].mean():.1f}%  |  Median: {df['pident_pct'].median():.1f}%")
    print(f"  Mean aln length: {df['alnlen'].mean():.0f} bp  |  Range: {df['alnlen'].min()}-{df['alnlen'].max()}")
    print(f"  Identity: 100%={exact}  >=90%={high}  80-90%={med}  <80%={low}")
    print(f"  1-to-1: {single} ({single/uq*100:.1f}%)  |  Multi-match: {multi} ({multi/uq*100:.1f}%)  |  Max repeats: {qc.max()}")
    return n, uq, ut


def load_nucmer_coords(path):
    """Parse nucmer show-coords output → dict[(d39v_pos, tigr4_pos)] = block_info."""
    blocks = []
    with open(path) as f:
        for line in f:
            if not line.strip() or line.startswith("/") or line.startswith("NUCMER") or \
               line.startswith("=") or line.startswith("    [S1]"):
                continue
            parts = line.strip().split("|")
            if len(parts) < 5:
                continue
            try:
                d_coords = parts[0].strip().split()
                t_coords = parts[1].strip().split()
                lens = parts[2].strip().split()
                pct_str = parts[3].strip().split()
                d_s, d_e = int(d_coords[0]), int(d_coords[1])
                t_s, t_e = int(t_coords[0]), int(t_coords[1])
                pct = float(pct_str[0]) if pct_str else 0.0
                blocks.append({"d39v_s": d_s, "d39v_e": d_e,
                               "tigr4_s": t_s, "tigr4_e": t_e,
                               "pident": pct})
            except (ValueError, IndexError):
                continue
    return blocks


def compute_bidirectional(df_fwd, df_rev):
    """Compute union and intersection of forward + reverse pairs."""
    fwd_pairs = set(zip(df_fwd["query"], df_fwd["target"]))
    rev_pairs = set(zip(df_rev["query"], df_rev["target"]))
    # In reverse, query=TIGR4, target=D39V. Normalize to (D39V, TIGR4)
    rev_norm = set((t, q) for q, t in rev_pairs)

    union_pairs = fwd_pairs | rev_norm
    inter_pairs = fwd_pairs & rev_norm
    fwd_only = fwd_pairs - rev_norm
    rev_only = rev_norm - fwd_pairs

    # Build DataFrames
    def pairs_to_df(pairs, label):
        if not pairs:
            return pd.DataFrame(columns=COLS + ["pident_pct"])
        rows = []
        for d, t in pairs:
            rows.append({"query": d, "target": t, "pident": 0, "alnlen": 0,
                         "mismatch": 0, "gapopen": 0, "qstart": 0, "qend": 0,
                         "tstart": 0, "tend": 0, "evalue": 0, "bits": 0,
                         "pident_pct": 0})
        return pd.DataFrame(rows)

    return {
        "union": pairs_to_df(union_pairs, "union"),
        "intersection (RBH)": pairs_to_df(inter_pairs, "intersection"),
        "fwd_only": pairs_to_df(fwd_only, "fwd_only"),
        "rev_only": pairs_to_df(rev_only, "rev_only"),
    }, len(union_pairs), len(inter_pairs), len(fwd_only), len(rev_only)


def orient_stats(df, d39v_meta, tigr4_meta):
    """Stratify by normalized orientation."""
    def norm_orient(x):
        return x.replace("(++)", "").replace("(--)", "").replace("(+-)", "").replace("(-+)", "")

    d39v_orient = df["query"].map(lambda x: norm_orient(d39v_meta.get(x, {}).get("orientation_type", "").strip("\r")))
    tigr4_orient = df["target"].map(lambda x: norm_orient(tigr4_meta.get(x, {}).get("orientation_type", "").strip("\r")))

    df["orient_d39v"] = d39v_orient
    df["orient_tigr4"] = tigr4_orient
    df["same_orient"] = d39v_orient == tigr4_orient

    print(f"\n{'='*60}")
    print(f"  CONSERVATION BY ORIENTATION TYPE")
    print(f"{'='*60}")

    for o in ["DIVERGENT", "CONVERGENT", "TANDEM", "UNKNOWN"]:
        subset = df[df["orient_d39v"] == o]
        if len(subset) > 0:
            same = subset["same_orient"].sum()
            print(f"  {o:<12} pairs={len(subset):>5}  same_orient={same} ({same/len(subset)*100:.1f}%)")


def nucmer_overlap(df, blocks, d39v_meta, tigr4_meta):
    """Cross MMseqs2 pairs with nucmer colinear blocks using genomic coordinates."""
    if not blocks:
        return
    overlapping = 0
    total_checked = 0

    for _, row in df.iterrows():
        q_id = row["query"]
        t_id = row["target"]
        q_igr = d39v_meta.get(q_id, {})
        t_igr = tigr4_meta.get(t_id, {})
        if not q_igr or not t_igr:
            continue

        try:
            d_start = int(q_igr.get("start", 0))
            t_start = int(t_igr.get("start", 0))
        except (ValueError, TypeError):
            continue

        qs = d_start + int(row.get("qstart", 0) or 0) - 1
        qe = d_start + int(row.get("qend", 0) or 0) - 1
        ts = t_start + int(row.get("tstart", 0) or 0) - 1
        te = t_start + int(row.get("tend", 0) or 0) - 1

        if qs > qe:
            qs, qe = qe, qs
        if ts > te:
            ts, te = te, ts

        total_checked += 1
        for blk in blocks:
            if max(qs, blk["d39v_s"]) <= min(qe, blk["d39v_e"]) and \
               max(ts, blk["tigr4_s"]) <= min(te, blk["tigr4_e"]):
                overlapping += 1
                break

    print(f"\n{'='*60}")
    print(f"  Nucmer CROSS-VALIDATION")
    print(f"{'='*60}")
    print(f"  Nucmer blocks: {len(blocks)}")
    print(f"  MMseqs2 pairs overlapping nucmer blocks: {overlapping}/{total_checked} ({overlapping/total_checked*100:.1f}%)")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--mode", choices=["forward", "reverse", "bidir"], default="forward")
    parser.add_argument("--nucmer", type=str, default=None)
    parser.add_argument("--separate-repeats", action="store_true")
    parser.add_argument("--by-orientation", action="store_true")
    args = parser.parse_args()

    print("Loading IGR metadata...")
    d39v_meta = load_igr_metadata(D39V_TSV)
    tigr4_meta = load_igr_metadata(TIGR4_TSV)

    if args.mode in ("forward", "bidir"):
        df_fwd = load_m8(M8_FWD)
    if args.mode in ("reverse", "bidir"):
        df_rev = load_m8(M8_REV)

    if args.mode == "forward":
        print_stats(df_fwd, "D39V → TIGR4", total_queries=len(d39v_meta),
                    total_targets=len(tigr4_meta))
    elif args.mode == "reverse":
        print_stats(df_rev, "TIGR4 → D39V", total_queries=len(tigr4_meta),
                    total_targets=len(d39v_meta))
    elif args.mode == "bidir":
        print_stats(df_fwd, "D39V → TIGR4 (forward)", total_queries=len(d39v_meta),
                    total_targets=len(tigr4_meta))
        print_stats(df_rev, "TIGR4 → D39V (reverse)", total_queries=len(tigr4_meta),
                    total_targets=len(d39v_meta))

        bidir_dfs, n_union, n_inter, n_fwd_only, n_rev_only = compute_bidirectional(df_fwd, df_rev)

        print(f"\n{'='*60}")
        print(f"  BIDIRECTIONAL SUMMARY")
        print(f"{'='*60}")
        print(f"  Forward only (D39V→TIGR4):  {n_fwd_only:,}")
        print(f"  Reverse only (TIGR4→D39V):  {n_rev_only:,}")
        print(f"  Union (total unique pairs):  {n_union:,}")
        print(f"  Intersection (reciprocal):   {n_inter:,}")
        print(f"  Asymmetry: {n_rev_only}/{n_fwd_only+n_inter+n_rev_only*1:.1f} rev-only, "
              f"{n_fwd_only}/{n_fwd_only+n_inter+n_rev_only*1:.1f} fwd-only")

    # Nucmer validation
    if args.nucmer:
        df = df_fwd if args.mode != "reverse" else df_rev
        blocks = load_nucmer_coords(Path(args.nucmer))
        nucmer_overlap(df, blocks, d39v_meta, tigr4_meta)

    # Orientation stratification
    if args.by_orientation:
        df = df_fwd if args.mode != "reverse" else df_rev
        orient_stats(df, d39v_meta, tigr4_meta)

    # Separate repeats
    if args.separate_repeats:
        df = df_fwd if args.mode != "reverse" else df_rev
        qc = df["query"].value_counts()
        repeats = set(qc[qc > 1].index)
        n_repeat_pairs = sum(qc[q] for q in repeats)
        n_unique_pairs = len(df) - n_repeat_pairs
        print(f"\n{'='*60}")
        print(f"  REPETITIVE ELEMENT FILTER")
        print(f"{'='*60}")
        print(f"  Repeat IGRs (>1 match): {len(repeats)}")
        print(f"  Pairs from repeats:     {n_repeat_pairs} ({n_repeat_pairs/len(df)*100:.1f}%)")
        print(f"  Unique 1-to-1 pairs:    {n_unique_pairs} ({n_unique_pairs/len(df)*100:.1f}%)")
        print(f"  After removing repeats:  {len(df) - n_repeat_pairs} high-confidence pairs")


if __name__ == "__main__":
    main()
