#!/usr/bin/env python3
"""
Canonical Master Analysis & Plotting Pipeline for promoter-tools.
Processes outputs generated by the CLI (predictions, metrics, scaling tables)
and generates standardized, publication-grade figures:

Modes:
  --mode baseline: Generates canonical baseline figures (1 CPU, 16 CPU, GPU, ROC N=1,976).
  --mode scaling:  Generates multi-scale scaling curves, speedup, and grouped bar charts.
  --mode all:      (Default) Generates the complete benchmark and scaling suite.

Usage:
  pixi run python src/analysis/generate_master_plots.py
  pixi run python src/analysis/generate_master_plots.py --mode baseline
  pixi run python src/analysis/generate_master_plots.py --mode scaling
  pixi run python src/analysis/generate_master_plots.py -o output/plots/my_plots
"""

import os
import argparse
import sys
import numpy as np
import pandas as pd
import matplotlib; matplotlib.use("Agg")
import matplotlib.pyplot as plt
from pathlib import Path
from sklearn.metrics import roc_curve, auc

ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(ROOT))
DEFAULT_OUT = ROOT / "output" / "plots" / "organized"
DEFAULT_DATA_DIR = Path(os.environ.get("PROMOTER_DATA_DIR", "/home/fierro/Desktop"))
TABLES_DIR = ROOT / "output" / "tables"
PRED_DIR = ROOT / "output" / "predictions"

PALETTE = {
    "MLDSPP XGBoost":           {"short": "MLDSPP",      "method": "BDT",   "color": "#D81B60", "marker": "v"},
    "MLDSPP XGBoost (75% spn)": {"short": "MLDSPP 75%",  "method": "BDT",   "color": "#942C76", "marker": "^"},
    "PromoterLCNN":             {"short": "PromoterLCNN","method": "CNN",   "color": "#228B22", "marker": "s"},
    "FIMO + Prokaryote DB":     {"short": "FIMO",        "method": "motif", "color": "#00ACC1", "marker": "D"},
    "PromoTech RF-HOT (PG Max)":{"short": "PromoTech",   "method": "RF",    "color": "#E65100", "marker": "P"},
    "iPro-MP (H. pylori)":      {"short": "iPro-MP",     "method": "gLM",   "color": "#3D185A", "marker": "o"},
    "MEME Suite (STREME+FIMO)": {"short": "MEME",        "method": "motif", "color": "#1E88E5", "marker": "X"},
}

KEY_SCALES = [1976, 19760, 98800, 395200]
SCALE_COLORS = {1976: "#90A4AE", 19760: "#42A5F5", 98800: "#FFA726", 395200: "#EF5350"}
SCALE_LABELS = {1976: "1.9k (1x)", 19760: "19.7k (10x)", 98800: "98.8k (50x)", 395200: "395.2k (200x)"}


def load_metrics(data_dir: Path, campaign: str, iteration: str) -> pd.DataFrame:
    """Load campaign metrics for one iteration; dedupe by tool."""
    root = data_dir / campaign / iteration / "predictions"
    frames = []
    if root.is_dir():
        for t in sorted(root.glob("resource_metrics*.tsv")):
            try:
                frames.append(pd.read_csv(t, sep="\t"))
            except Exception:
                continue
    if not frames:
        return pd.DataFrame()
    df = pd.concat(frames, ignore_index=True)
    if "success" in df.columns:
        df = df[df["success"].fillna(False).astype(bool)]
    if "tool" in df.columns:
        df = df.drop_duplicates(subset=["tool"], keep="last")
    return df


def metric_row(df: pd.DataFrame, tool_name: str) -> dict:
    sub = df[df["tool"] == tool_name]
    if sub.empty:
        return {}
    r = sub.iloc[0]
    return {c: r[c] for c in ["time_s", "peak_ram_mb", "peak_vram_mb", "model_size_mb",
                              "n_sequences"] if c in r and pd.notna(r[c])}


def save_fig(fig, out_dir, name, secondary_out=None):
    out_dir.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_dir / f"{name}.png", dpi=300, bbox_inches="tight")
    fig.savefig(out_dir / f"{name}.svg", dpi=300, bbox_inches="tight")
    if secondary_out:
        secondary_out.mkdir(parents=True, exist_ok=True)
        fig.savefig(secondary_out / f"{name}.png", dpi=300, bbox_inches="tight")
        fig.savefig(secondary_out / f"{name}.svg", dpi=300, bbox_inches="tight")
    print(f"  [Saved] {out_dir.name}/{name}.png and .svg")


def generate_baseline_plots(base_out, sec_out=None, data_dir=DEFAULT_DATA_DIR):
    dir_1cpu = base_out / "1_cpu"
    dir_16cpu = base_out / "16_cpu"
    dir_gpu = base_out / "gpu_vram"

    sec_1cpu = sec_out / "1_cpu" if sec_out else None
    sec_16cpu = sec_out / "16_cpu" if sec_out else None
    sec_gpu = sec_out / "gpu_vram" if sec_out else None

    m1 = load_metrics(data_dir, "scale_db", "988")
    m16 = load_metrics(data_dir, "scale_db_16cpu", "988")
    mgpu = load_metrics(data_dir, "scale_db_gpu_thr1", "988")
    if mgpu.empty:
        mgpu = load_metrics(data_dir, "scale_db_4tools", "988")

    def rows_from(df, tools=None):
        rows = []
        for name in df["tool"].unique():
            if tools and name not in tools:
                continue
            r = metric_row(df, name)
            if not r or "time_s" not in r:
                continue
            meta = PALETTE.get(name, {"short": name.split(" (")[0], "method": "?", "color": "#666666"})
            rows.append({"name": f"{meta['short']}\n({meta['method']})", "color": meta["color"],
                         "time": float(r["time_s"]), "ram": float(r.get("peak_ram_mb", 0))})
        return rows

    n1 = int(m1["n_sequences"].iloc[0]) if not m1.empty and "n_sequences" in m1.columns else 1976

    tools_1cpu = rows_from(m1)

    # 1 CPU Baseline
    if tools_1cpu:
        fig, ax = plt.subplots(figsize=(10, 6.5), dpi=300)
        x = np.arange(len(tools_1cpu))
        bars = ax.bar(x, [t["time"] for t in tools_1cpu], 0.52, color=[t["color"] for t in tools_1cpu], edgecolor="black", linewidth=0.8, zorder=3)
        for bar in bars:
            h = bar.get_height()
            txt = f"{h:.1f} s\n({h/60:.1f} min)" if h >= 60 else f"{h:.2f} s"
            ax.annotate(txt, (bar.get_x() + bar.get_width()/2, h), xytext=(0, 5), textcoords="offset points", ha='center', va='bottom', fontsize=9.5, fontweight='bold')
        ax.set_xticks(x); ax.set_xticklabels([t["name"] for t in tools_1cpu], fontsize=11, fontweight="bold")
        ax.set_xlabel("Tool", fontsize=12, fontweight="bold", labelpad=10)
        ax.set_ylabel("Inference Time (s)", fontsize=12, fontweight="bold")
        ax.set_title(f"Single-Core CPU Inference Time (N = {n1:,})", fontsize=13, fontweight="bold", pad=15)
        ax.set_ylim(0, max(t["time"] for t in tools_1cpu) * 1.12); ax.grid(True, axis="y", linestyle="--", alpha=0.5, zorder=0)
        ax.spines[["top", "right"]].set_visible(False)
        plt.tight_layout()
        save_fig(fig, dir_1cpu, "compute_time_baseline", sec_1cpu)
        plt.close(fig)

        # RAM 1 CPU
        fig, ax = plt.subplots(figsize=(10, 6.5), dpi=300)
        bars = ax.bar(x, [t["ram"] for t in tools_1cpu], 0.52, color=[t["color"] for t in tools_1cpu], edgecolor="black", linewidth=0.8, zorder=3)
        for bar in bars:
            h = bar.get_height()
            txt = f"{h/1024:.2f} GB" if h >= 1000 else f"{h:.0f} MB"
            ax.annotate(txt, (bar.get_x() + bar.get_width()/2, h), xytext=(0, 5), textcoords="offset points", ha='center', va='bottom', fontsize=9.5, fontweight='bold')
        ax.set_xticks(x); ax.set_xticklabels([t["name"] for t in tools_1cpu], fontsize=11, fontweight="bold")
        ax.set_xlabel("Tool", fontsize=12, fontweight="bold", labelpad=10)
        ax.set_ylabel("Peak RAM (MB)", fontsize=12, fontweight="bold")
        ax.set_title(f"Single-Core CPU Peak RAM Usage (N = {n1:,})", fontsize=13, fontweight="bold", pad=15)
        ax.set_ylim(0, max(t["ram"] for t in tools_1cpu) * 1.12); ax.grid(True, axis="y", linestyle="--", alpha=0.5, zorder=0)
        ax.spines[["top", "right"]].set_visible(False)
        plt.tight_layout()
        save_fig(fig, dir_1cpu, "peak_memory_baseline", sec_1cpu)
        plt.close(fig)

    # 16 CPU Baseline Time
    tools_16cpu = rows_from(m16)
    if tools_16cpu:
        fig, ax = plt.subplots(figsize=(10, 6.5), dpi=300)
        x16 = np.arange(len(tools_16cpu))
        bars = ax.bar(x16, [t["time"] for t in tools_16cpu], 0.52, color=[t["color"] for t in tools_16cpu], edgecolor="black", linewidth=0.8, zorder=3)
        for bar in bars:
            h = bar.get_height()
            txt = f"{h:.2f} s" if h < 60 else f"{h:.1f} s"
            ax.annotate(txt, (bar.get_x() + bar.get_width()/2, h), xytext=(0, 5), textcoords="offset points", ha='center', va='bottom', fontsize=10, fontweight='bold')
        ax.set_xticks(x16); ax.set_xticklabels([t["name"] for t in tools_16cpu], fontsize=11, fontweight="bold")
        ax.set_xlabel("Tool", fontsize=12, fontweight="bold", labelpad=10)
        ax.set_ylabel("Inference Time (s)", fontsize=12, fontweight="bold")
        ax.set_title(f"16-Core CPU Inference Time (N = {n1:,})", fontsize=13, fontweight="bold", pad=15)
        ax.set_ylim(0, max(t["time"] for t in tools_16cpu) * 1.12); ax.grid(True, axis="y", linestyle="--", alpha=0.5, zorder=0)
        ax.spines[["top", "right"]].set_visible(False)
        plt.tight_layout()
        save_fig(fig, dir_16cpu, "compute_time_baseline", sec_16cpu)
        plt.close(fig)

    # GPU Baseline Weights vs VRAM (from metrics)
    gpu_names = ["PromoterLCNN", "iPro-MP (H. pylori)"]
    gpu_models = []
    weights_size_mb = []
    inference_vram_mb = []
    for gn in gpu_names:
        r = metric_row(mgpu, gn)
        if not r:
            continue
        meta = PALETTE.get(gn, {"short": gn.split(" (")[0], "color": "#666666"})
        gpu_models.append(f"{meta['short']}\n({PALETTE.get(gn, {}).get('method', '?')})")
        weights_size_mb.append(float(r.get("model_size_mb", 0)))
        inference_vram_mb.append(float(r.get("peak_vram_mb", 0)))
    if gpu_models:
        fig, ax = plt.subplots(figsize=(9, 6), dpi=300)
        xg = np.arange(len(gpu_models)); w = 0.35
        b1 = ax.bar(xg - w/2, weights_size_mb, w, label="Model Weights (Disk/RAM)", color="#455A64", edgecolor="black", linewidth=0.8, zorder=3)
        b2 = ax.bar(xg + w/2, inference_vram_mb, w, label="Peak Inference VRAM", color="#7B1FA2", edgecolor="black", linewidth=0.8, zorder=3)
        for bar in b1:
            h = bar.get_height()
            ax.annotate(f"{h:.1f} MB", (bar.get_x() + bar.get_width()/2, h), xytext=(0, 5), textcoords="offset points", ha='center', va='bottom', fontsize=10, fontweight='bold')
        for bar in b2:
            h = bar.get_height()
            ax.annotate(f"{h:.0f} MB\n({h/1024:.2f} GB)", (bar.get_x() + bar.get_width()/2, h), xytext=(0, 5), textcoords="offset points", ha='center', va='bottom', fontsize=10, fontweight='bold')
        ax.set_ylabel("Memory (MB)", fontsize=12, fontweight="bold")
        ax.set_title(f"GPU Memory Requirements: Model Weights vs Peak VRAM (N = {n1:,})", fontsize=13, fontweight="bold", pad=15)
        ax.set_xticks(xg); ax.set_xticklabels(gpu_models, fontsize=11, fontweight="bold")
        ax.set_ylim(0, max(inference_vram_mb + weights_size_mb + [1]) * 1.12); ax.grid(True, axis="y", linestyle="--", alpha=0.5, zorder=0)
        ax.spines[["top", "right"]].set_visible(False)
        ax.legend(frameon=True, fontsize=10, loc="upper left")
        plt.tight_layout()
        save_fig(fig, dir_gpu, "peak_memory_baseline", sec_gpu)
        plt.close(fig)


def generate_roc_curves(base_out, sec_out=None):
    if not (PRED_DIR / "mldspp_pos.csv").exists():
        return
    curves = []

    # iPro-MP
    if (PRED_DIR / 'ipromp' / 'ipromp_12_predictions.csv').exists():
        from src.config import config
        df_ip = pd.read_csv(PRED_DIR / 'ipromp' / 'ipromp_12_predictions.csv')
        n_pos = config.n_positives if len(df_ip) >= config.n_total else len(df_ip) // 2
        n_neg = len(df_ip) - n_pos
        y = np.hstack([np.ones(n_pos), np.zeros(n_neg)])
        col = 'Probability' if 'Probability' in df_ip.columns else 'PRED'
        fpr, tpr, _ = roc_curve(y, df_ip[col].values)
        curves.append(("iPro-MP (gLM)", fpr, tpr, auc(fpr, tpr), "#3D185A", "-", 2.4))

    # LCNN
    if (PRED_DIR / 'lcnn' / 'lcnn_pos.csv').exists():
        pos = pd.read_csv(PRED_DIR / 'lcnn' / 'lcnn_pos.csv', sep='\t')
        neg = pd.read_csv(PRED_DIR / 'lcnn' / 'lcnn_neg.csv', sep='\t')
        y = np.hstack([np.ones(len(pos)), np.zeros(len(neg))])
        fpr, tpr, _ = roc_curve(y, np.hstack([pos['PRED'].values, neg['PRED'].values]))
        curves.append(("PromoterLCNN (CNN)", fpr, tpr, auc(fpr, tpr), "#228B22", "-", 2.4))

    # PromoTech
    if (PRED_DIR / 'promotech/workdir/hot_pg_pos/sequences_predictions.csv').exists():
        pos = pd.read_csv(PRED_DIR / 'promotech/workdir/hot_pg_pos/sequences_predictions.csv', sep='\t')
        neg = pd.read_csv(PRED_DIR / 'promotech/workdir/hot_pg_neg/sequences_predictions.csv', sep='\t')
        y = np.hstack([np.ones(len(pos)), np.zeros(len(neg))])
        fpr, tpr, _ = roc_curve(y, np.hstack([pos['PRED'].values, neg['PRED'].values]))
        curves.append(("PromoTech (RF)", fpr, tpr, auc(fpr, tpr), "#E65100", "-", 2.2))

    # MLDSPP
    if (PRED_DIR / 'mldspp_pos.csv').exists():
        pos = pd.read_csv(PRED_DIR / 'mldspp_pos.csv', sep='\t')
        neg = pd.read_csv(PRED_DIR / 'mldspp_neg.csv', sep='\t')
        y = np.hstack([np.ones(len(pos)), np.zeros(len(neg))])
        fpr, tpr, _ = roc_curve(y, np.hstack([pos['PRED'].values, neg['PRED'].values]))
        curves.append(("MLDSPP (BDT)", fpr, tpr, auc(fpr, tpr), "#D81B60", "-", 2.2))

    # FIMO
    if (PRED_DIR / 'fimo_prok_pos.csv').exists():
        pos = pd.read_csv(PRED_DIR / 'fimo_prok_pos.csv', sep='\t')
        neg = pd.read_csv(PRED_DIR / 'fimo_prok_neg.csv', sep='\t')
        y = np.hstack([np.ones(len(pos)), np.zeros(len(neg))])
        fpr, tpr, _ = roc_curve(y, np.hstack([pos['PRED'].values, neg['PRED'].values]))
        curves.append(("FIMO (motif)", fpr, tpr, auc(fpr, tpr), "#00ACC1", "-.", 2.0))

    fig, ax = plt.subplots(figsize=(9, 7.5), dpi=300)
    for name, fpr, tpr, a, color, ls, lw in curves:
        ax.plot(fpr, tpr, color=color, linestyle=ls, linewidth=lw, label=f"{name} (AUC = {a:.4f})")
    ax.plot([0, 1], [0, 1], color="#9E9E9E", linestyle="--", linewidth=1.2, label="Random Chance (AUC = 0.500)")
    ax.set_xlabel("False Positive Rate (1 - Specificity)", fontsize=12, fontweight="bold")
    ax.set_ylabel("True Positive Rate (Sensitivity)", fontsize=12, fontweight="bold")
    ax.set_title("Receiver Operating Characteristic (ROC) — N = 1,976", fontsize=13, fontweight="bold", pad=15)
    ax.set_xlim([0.0, 1.0]); ax.set_ylim([0.0, 1.02])
    ax.grid(True, linestyle="--", alpha=0.4); ax.spines[["top", "right"]].set_visible(False)
    ax.legend(frameon=True, fontsize=10, loc="lower right", framealpha=0.95)
    plt.tight_layout()

    for r in ["1_cpu", "16_cpu", "gpu_vram"]:
        sec_r = sec_out / r if sec_out else None
        save_fig(fig, base_out / r, "roc_auc_N1976", sec_r)
    plt.close(fig)


def main():
    p = argparse.ArgumentParser(description="Master Plot Pipeline for promoter-tools")
    p.add_argument("-o", "--output-dir", default=str(DEFAULT_OUT), help="Target output dir")
    p.add_argument("--mode", choices=["all", "baseline", "scaling"], default="all", help="Execution mode")
    p.add_argument("--sync-desktop", action="store_true", default=True, help="Also mirror outputs to Desktop organized folder")
    p.add_argument("--desktop-out", default=str(ROOT / "output/plots/benchmark_organized"), help="Mirror output dir")
    p.add_argument("--data-dir", default=str(DEFAULT_DATA_DIR), help="Base dir with scale_db campaign folders")
    args = p.parse_args()

    out_base = Path(args.output_dir)
    sec_base = Path(args.desktop_out) if args.sync_desktop else None
    data_dir = Path(args.data_dir)

    print("=" * 75)
    print(f"  EJECUTANDO MASTER ANALYSIS & PLOT GENERATOR (Mode: {args.mode})")
    print(f"  Canonical directory: {out_base}")
    if sec_base:
        print(f"  Directorio Espejo:   {sec_base}")
    print("=" * 75)

    if args.mode in ["all", "baseline"]:
        generate_baseline_plots(out_base, sec_base, data_dir=data_dir)
        generate_roc_curves(out_base, sec_base)

    if args.mode in ["all", "scaling"]:
        from src.analysis.scaling_analysis import main as run_scaling
        run_scaling()

    print("\n" + "=" * 75)
    print("  GENERATION PIPELINE COMPLETED SUCCESSFULLY")
    print("=" * 75)


if __name__ == "__main__":
    main()
